FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
CMD ["sh", "-c", "npm run build && find dist -type f \\( -name '*.js' -o -name '*.css' -o -name '*.html' \\) -exec gzip -f -k {} \\;"]
